#!/bin/bash

/wait-for-step.sh
/execute-step.sh
KAFKA_STARTUP="kafka-startup.json"
KAFKA_INIT="kafka-init.json"
if [ -f $KAFKA_STARTUP ]; then
  /app/bin/kafka-bin.py $KAFKA_STARTUP
  if [ -f $KAFKA_INIT ]; then
    /app/bin/kafka-bin.py $KAFKA_INIT
  fi
fi
/finish-step.sh
